---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbox
  namespace: &ns networking
spec:
  components:
    - ../../../../components/dragonfly
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 10m
  path: ./kubernetes/apps/networking/netbox/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      APP: netbox
    substituteFrom:
      - kind: Secret
        name: netbox-secrets
