---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager
  namespace: *app
spec:
  targetNamespace: *app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/cluster/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-self-signed
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager-self-signed
  interval: 30m
  timeout: 5m
  path: ./kubernetes/cluster/cert-manager/self-signed
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager-issuers
  interval: 30m
  timeout: 5m
  path: ./kubernetes/cluster/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certificates
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager-certificates
  interval: 30m
  timeout: 5m
  path: ./kubernetes/cluster/cert-manager/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
