---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
spec:
  postgresVersion: 18
  service:
    type: LoadBalancer
    metadata:
      annotations:
        io.cilium/lb-ipam-ips: "10.0.0.210"
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        pg_hba:
          - "local all all trust"
          - "host all all 127.0.0.1/32 md5"
          - "host all all ::1/128 md5"
          - "local replication standby trust"
          - "hostssl replication standby all md5"
          - "host all all 10.244.0.0/16 md5"
          - "host all all 0.0.0.0/0 md5"
          - "hostssl all all 0.0.0.0/0 md5"
        parameters:
          shared_buffers: "256MB"
          effective_cache_size: "768MB"
          maintenance_work_mem: "192MB"
          checkpoint_completion_target: "0.9"
          wal_buffers: "16MB"
          default_statistics_target: "100"
          random_page_cost: "1.1"
          effective_io_concurrency: "200"
          work_mem: "4MB"
          min_wal_size: "2GB"
          max_wal_size: "8GB"
          max_worker_processes: "4"
          max_parallel_workers_per_gather: "2"
          max_parallel_workers: "4"
          max_connections: "500"
          synchronous_commit: "on"
  instances:
    - name: pg-instance
      replicas: 3
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      dataVolumeClaimSpec:
        storageClassName: ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  users:
    - name: mafyuh
      databases: ["authentik", "gatus", "jellyseerr", "netbox", "umami"]
      options: "SUPERUSER"
    - name: authentik
      databases: ["authentik"]
    - name: gatus
      databases: ["gatus"]
    - name: jellyseerr
      databases: ["jellyseerr"]
    - name: matrix
      databases: ["matrix", "matrixauth"]
    - name: netbox
      databases: ["netbox"]
    - name: umami
      databases: ["umami"]
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pg-cluster-crunchy-postgres
      global:
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /pg-cluster
        repo1-retention-full: "7"
        repo1-retention-full-type: time
        repo1-s3-uri-style: path
      jobs:
        ttlSecondsAfterFinished: 60
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3:
            bucket: postgres
            endpoint: "https://s3.mafyuh.xyz"
            region: us-east-1
          schedules:
            full: "30 0 * * *"
