---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: security
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.security.svc.cluster.local
    - REDACTED.security.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
