---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - external-secrets.yaml
  - pvc.yaml
  - replicationsource.yaml
  - replicationdestination.yaml
