---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-instance
  namespace: flux-system
resources:
  - helmrelease.yaml
  - httproute.yaml
  - receiver.yaml
  - external-secret.yaml
  - source.yaml
  - dashboard.yaml
  - monitoring.yaml
