---
kopia_server_url: "https://10.0.0.6:51515"
kopia_server_cert_fingerprint: "REDACTED"

kopia_snapshots:
  - path: "/home"
    description: "Home directory backup"
  - path: "/docker"
    description: "Docker directory backup"
