---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox/ks.yaml
  - fluent-bit/ks.yaml
  - gatus/ks.yaml
  - grafana/ks.yaml
  - headlamp/ks.yaml
  - keda/ks.yaml
  - kromgo/ks.yaml
  - prometheus/ks.yaml
  - umami/ks.yaml
  - unpoller/ks.yaml
  - victoria-logs/ks.yaml
