---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app headlamp
  namespace: &ns monitoring
spec:
  targetNamespace: *ns
  components:
    - ../../../../components/authentik-proxy
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/monitoring/headlamp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  postBuild:
    substitute:
      APP: headlamp
  wait: false
