---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-secrets
  namespace: matrix
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: PG_PASSWORD
      remoteRef:
        key: "REDACTED"
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: "REDACTED"
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: "REDACTED"
