ARM:
  env_variables:
    GOTIFY_DEFAULTUSER_NAME: REDACTED
    GOTIFY_DEFAULTUSER_PASS: REDACTED
    HTTP_SERVER_NAME: REDACTED
    SERVER_ADMIN: REDACTED
    WEBHOOK_URL: REDACTED
    GITEA__database__PASSWD: REDACTED
    MYSQL_ROOT_PASSWORD: REDACTED
    MYSQL_PASSWORD: REDACTED
    VWDOMAIN: REDACTED
    GITEA_API_TOKEN: REDACTED
    CLOUDFLARE_EMAIL: REDACTED
    CF_DNS_API_TOKEN: REDACTED
    CF_ZONE_API_TOKEN: REDACTED
    COMPOSE_PROJECT_NAME: REDACTED
    DB_PASS: REDACTED
    SSMTP_HOST: REDACTED
    SSMTP_USER: REDACTED
    SSMTP_PASSWORD: REDACTED
    SSMTP_HOSTNAME: REDACTED
    POSTGRES_PASSWORD: REDACTED
    NEXTAUTH_URL: REDACTED
    NEXTAUTH_SECRET: REDACTED
    NEXT_PUBLIC_AUTHENTIK_ENABLED: REDACTED
    AUTHENTIK_CUSTOM_NAME: REDACTED
    AUTHENTIK_ISSUER: REDACTED
    AUTHENTIK_CLIENT_ID: REDACTED
    AUTHENTIK_CLIENT_SECRET: REDACTED
    SMTP_PASSWORD: REDACTED
    SSO_CLIENT_SECRET: REDACTED
    DATABASE_URL: REDACTED

db-server:
  env_variables:
    MYSQL_ROOT_PASSWORD: REDACTED
    MYSQL_PASSWORD: REDACTED
    POSTGRES_PASSWORD: REDACTED
    PGADMIN_DEFAULT_PASSWORD: REDACTED
    PGADMIN_CONFIG_OAUTH2_CONFIG: REDACTED
    COUCHDB_PASSWORD: REDACTED
    RUSTFS_ACCESS_KEY: REDACTED
    RUSTFS_SECRET_KEY: REDACTED
    MINIO_ROOT_PASSWORD: REDACTED

blocky-HA:
  env_variables:
    PGPASSWORD: REDACTED

Ark-Ripper:
  env_variables:
    COMPOSE_PROJECT_NAME: REDACTED
    MAKEMKV_KEY: REDACTED

Kasm:
  env_variables:
    DOCKER_HUB_PASSWORD: REDACTED
    DOCKER_HUB_USERNAME: REDACTED
    COUCHDB_PASSWORD: REDACTED

Nginx-Proxy-Manager:
  env_variables:
    SSMTP_HOST: REDACTED
    SSMTP_USER: REDACTED
    SSMTP_PASSWORD: REDACTED
    SSMTP_HOSTNAME: REDACTED
    CF_TOKEN: REDACTED
    TWINGATE_NETWORK: REDACTED
    TWINGATE_ACCESS_TOKEN: REDACTED
    TWINGATE_REFRESH_TOKEN: REDACTED
    COMPOSE_PROJECT_NAME: REDACTED

Ubu:
  env_variables:
    GF_SECURITY_ADMIN_PASSWORD: REDACTED
    RADARR_API: REDACTED
    RADARR_URL: REDACTED
    SONARR_API: REDACTED
    SONARR_URL: REDACTED
    PROWLARR_API: REDACTED
    PROWLARR_URL: REDACTED
    SAB_URL: REDACTED
    SAB_API: REDACTED
    BAZARR_API: REDACTED
    BAZARR_URL: REDACTED
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: REDACTED
    REDACTED: REDACTED
    GF_SERVER_ROOT_URL: REDACTED
    AUTHENTIK_URL: REDACTED
    PVE_PASSWORD: REDACTED
    JS_POSTGRES_PASSWORD: REDACTED
    JWT_SECRET: REDACTED
    JS_GEOLITE_LICENSE_KEY: REDACTED
    NEXT_PUBLIC_GOOGLE_API_KEY: REDACTED
    MONGO_INITDB_ROOT_PASSWORD: REDACTED
    DB_NAME: REDACTED
    NEXTAUTH_SECRET: REDACTED
    CRYPTR_SECRET: REDACTED

wazuh:
  env_variables:
    SMTP_PASSWORD: REDACTED

proxy:
  env_variables:
    CLOUDFLARE_API_TOKEN: REDACTED
    SSMTP_HOST: REDACTED
    SSMTP_USER: REDACTED
    SSMTP_PASSWORD: REDACTED
    SSMTP_HOSTNAME: REDACTED
