---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: kube-cpu-overcommit
spec:
  matchers:
    - name: alertname
      value: KubeCPUOvercommit
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: keda-hpa-maxed-out
spec:
  matchers:
    - name: alertname
      value: KubeHpaMaxedOut
    - name: horizontalpodautoscaler
      value: keda-hpa-.*
      matchType: "=~"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: cpu-throttling-high
spec:
  matchers:
    - name: alertname
      value: CPUThrottlingHigh
