---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: AUTHENTIK_POSTGRESQL_HOST
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_POSTGRESQL_NAME
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_POSTGRESQL_USER
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_POSTGRESQL_PASSWORD
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_POSTGRESQL_PORT
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_SMTP_PASSWORD
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: "REDACTED"
    - secretKey: AUTHENTIK_DOMAIN
      remoteRef:
        key: "REDACTED"
