---
# yaml-language-server: $schema=https://crd.movishell.pl/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authentik-service
  namespace: authentik
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: arr
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: monitoring
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: default
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: databases
  to:
    - group: ""
      kind: Service
      name: REDACTED
