---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twingate-secrets
  namespace: networking
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: TWINGATE_ACCESS_TOKEN
      remoteRef:
        key: "REDACTED"
    - secretKey: TWINGATE_REFRESH_TOKEN
      remoteRef:
        key: "REDACTED"
