sonarr:
  series:
    base_url: http://sonarr-app.arr.svc.cluster.local:8989
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: REDACTED
      - template: REDACTED
      - template: REDACTED
      - template: REDACTED
      - template: REDACTED

    # quality_profiles:
    #   - name: WEB-DL (1080p)
    #     reset_unmatched_scores:
    #       enabled: true
    #     upgrade:
    #       allowed: true
    #       until_quality: WEBDL-1080p
    #       until_score: 10000
    #     min_format_score: 1
    #     qualities:
    #       - WEBDL-1080p
    #       - WEBRip-1080p
    #       - HDTV-1080p

    custom_formats:
      - trash_ids:
          - REDACTED # Bad Dual Groups
          - REDACTED # BR-DISK
          - REDACTED # Obfuscated
          - REDACTED # x265 (720/1080p)
          - REDACTED # Scene
        assign_scores_to:
          - name: WEB-DL (1080p)
            score: -10000

      - trash_ids:
          - REDACTED # DV (WEBDL)
        assign_scores_to:
          - name: WEB-2160p

radarr:
  radarr_main:
    base_url: http://radarr-app.arr.svc.cluster.local:7878
    api_key: !env_var RADARR_API_KEY

    # Custom Format Configuration
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: radarr-quality-definition-movie
      - template: REDACTED
      - template: REDACTED
      - template: radarr-quality-definition-movie
      - template: REDACTED
      - template: REDACTED

    # quality_profiles:
    #   - name: HD Bluray + WEB
    #     min_format_score: 0
    #     reset_unmatched_scores:
    #       enabled: true
    #     qualities:
    #       - WEBDL-1080p
    #       - Bluray-1080p
    #   - name: UHD Bluray + WEB
    #     reset_unmatched_scores:
    #       enabled: true
    #     qualities:
    #       - WEBDL-2160p
    #       - Bluray-2160p
    #       - WEBDL-1080p  # Ensuring `until_quality` exists in the list

    custom_formats:
      - trash_ids:
          - REDACTED # Bad Dual Groups
          - REDACTED # EVO (no WEBDL)
          - REDACTED # No-RlsGroup
          - REDACTED # Obfuscated
          - REDACTED # Retags
          - REDACTED # Scene
        assign_scores_to:
          - name: HD Bluray + WEB
      - trash_ids:
          - REDACTED # IMAX
          - REDACTED # IMAX ENHANCED
          - REDACTED # DV HDR10+
          - REDACTED # DV HDR10
          - REDACTED # DV
          - REDACTED # DV HLG
          - REDACTED # DV SDR
          - REDACTED # HDR10+
          - REDACTED # HDR10
          - REDACTED # HDR
          - REDACTED # HDR Undefined
          - REDACTED # PQ
          - REDACTED # HLG
        assign_scores_to:
          - name: UHD Bluray + WEB
