---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner/ks.yaml
  - arr/
  - authentik/ks.yaml
  - databases/
  - default/
  - kopia/ks.yaml
  - matrix/ks.yaml
  - monitoring/
  - networking/
  - reflector/ks.yaml
  - reloader/ks.yaml
  - spegel/ks.yaml
  - tuppr/ks.yaml
  - twingate/ks.yaml
  - volsync/ks.yaml
