---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd
  namespace: &ns arr
spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/authentik-proxy
    - ../../../../components/nfs
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/arr/sabnzbd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      APP: sabnzbd
      VOLSYNC_CAPACITY: 2Gi
    substituteFrom:
      - kind: Secret
        name: arr-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nfs-cleaner
  namespace: &ns arr
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/arr/sabnzbd/nfs-cleaner
  prune: true
  sourceRef:
    kind: GitRepository
    name: iac
    namespace: flux-system
  wait: false
