---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - db.yaml
  - source.yaml
  - external-secret.yaml
configMapGenerator:
  - name: immich-database-init-sql
    options:
      disableNameSuffixHash: true
    files:
      - init.sql=./database-init-cm.sql
