plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.local.mafyuh.dev
validate_certs: true
config_context: false
group_by:
  - device_roles
query_filters:
  - tag: ansible
# device_query_filters:
#   - has_primary_ip: 'true'
#   - tenant__n: internal
token: "{{ lookup('community.general.bitwarden_secrets_manager', 'REDACTED').value }}"
compose:
  ansible_port: 2424
