---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: networking
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: NETBOX_ADMIN_PASSWORD
      remoteRef:
        key: "REDACTED"
    - secretKey: MAIN_PG_DB_HOST
      remoteRef:
        key: "REDACTED"
